/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/$owner/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as ApiGithubWebhookQueueRouteImport } from './routes/api/github/webhook-queue'
import { Route as ApiGithubWebhookProcessRouteImport } from './routes/api/github/webhook-process'
import { Route as ApiGithubWebhookHealthRouteImport } from './routes/api/github/webhook-health'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubRateLimitRouteImport } from './routes/api/github/rate-limit'
import { Route as ApiGithubPermissionsRouteImport } from './routes/api/github/permissions'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner/$repo/pulls'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner/$repo/issues'
import { Route as ApiGithubOauthIndexRouteImport } from './routes/api/github/oauth/index'
import { Route as ApiGithubSyncWebhooksRouteImport } from './routes/api/github/sync/webhooks'
import { Route as ApiGithubSyncRetryRouteImport } from './routes/api/github/sync/retry'
import { Route as ApiGithubSyncResetRouteImport } from './routes/api/github/sync/reset'
import { Route as ApiGithubSyncOverviewRouteImport } from './routes/api/github/sync/overview'
import { Route as ApiGithubSyncAddRepoRouteImport } from './routes/api/github/sync/add-repo'
import { Route as ApiGithubOauthCallbackRouteImport } from './routes/api/github/oauth/callback'
import { Route as OwnerRepoPullNumberRouteImport } from './routes/$owner/$repo/pull.$number'
import { Route as OwnerRepoIssuesNumberRouteImport } from './routes/$owner/$repo/issues.$number'
import { Route as OwnerRepoCommitsBranchRouteImport } from './routes/$owner/$repo/commits.$branch'
import { Route as ApiGithubSyncOwnerRepoRouteImport } from './routes/api/github/sync/$owner.$repo'
import { Route as ApiGithubReadmeOwnerRepoRouteImport } from './routes/api/github/readme/$owner.$repo'
import { Route as ApiGithubBranchOwnerRepoRouteImport } from './routes/api/github/branch.$owner.$repo'
import { Route as OwnerRepoTreeBranchSplatRouteImport } from './routes/$owner/$repo/tree.$branch.$'
import { Route as OwnerRepoBlobBranchSplatRouteImport } from './routes/$owner/$repo/blob.$branch.$'
import { Route as ApiGithubSyncOwnerRepoTreeRouteImport } from './routes/api/github/sync/$owner.$repo.tree'
import { Route as ApiGithubSyncOwnerRepoCommitsRouteImport } from './routes/api/github/sync/$owner.$repo.commits'
import { Route as ApiGithubSuggestionsOwnerRepoNumberRouteImport } from './routes/api/github/suggestions.$owner.$repo.$number'
import { Route as ApiGithubReviewsOwnerRepoNumberRouteImport } from './routes/api/github/reviews.$owner.$repo.$number'
import { Route as ApiGithubReviewCommentsOwnerRepoNumberRouteImport } from './routes/api/github/review-comments.$owner.$repo.$number'
import { Route as ApiGithubResolveOwnerRepoNumberRouteImport } from './routes/api/github/resolve.$owner.$repo.$number'
import { Route as ApiGithubFileOwnerRepoSplatRouteImport } from './routes/api/github/file/$owner.$repo.$'
import { Route as ApiGithubCommentsOwnerRepoNumberRouteImport } from './routes/api/github/comments.$owner.$repo.$number'
import { Route as ApiGithubSyncOwnerRepoPullNumberRouteImport } from './routes/api/github/sync/$owner.$repo.pull.$number'
import { Route as ApiGithubSyncOwnerRepoIssueNumberRouteImport } from './routes/api/github/sync/$owner.$repo.issue.$number'
import { Route as ApiGithubPrStateOwnerRepoNumberRouteImport } from './routes/api/github/pr.state.$owner.$repo.$number'
import { Route as ApiGithubPrMergeOwnerRepoNumberRouteImport } from './routes/api/github/pr.merge.$owner.$repo.$number'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookQueueRoute = ApiGithubWebhookQueueRouteImport.update({
  id: '/api/github/webhook-queue',
  path: '/api/github/webhook-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookProcessRoute = ApiGithubWebhookProcessRouteImport.update({
  id: '/api/github/webhook-process',
  path: '/api/github/webhook-process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookHealthRoute = ApiGithubWebhookHealthRouteImport.update({
  id: '/api/github/webhook-health',
  path: '/api/github/webhook-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRateLimitRoute = ApiGithubRateLimitRouteImport.update({
  id: '/api/github/rate-limit',
  path: '/api/github/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPermissionsRoute = ApiGithubPermissionsRouteImport.update({
  id: '/api/github/permissions',
  path: '/api/github/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/$owner/$repo/issues',
  path: '/$owner/$repo/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubOauthIndexRoute = ApiGithubOauthIndexRouteImport.update({
  id: '/api/github/oauth/',
  path: '/api/github/oauth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSyncWebhooksRoute = ApiGithubSyncWebhooksRouteImport.update({
  id: '/api/github/sync/webhooks',
  path: '/api/github/sync/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSyncRetryRoute = ApiGithubSyncRetryRouteImport.update({
  id: '/api/github/sync/retry',
  path: '/api/github/sync/retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSyncResetRoute = ApiGithubSyncResetRouteImport.update({
  id: '/api/github/sync/reset',
  path: '/api/github/sync/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSyncOverviewRoute = ApiGithubSyncOverviewRouteImport.update({
  id: '/api/github/sync/overview',
  path: '/api/github/sync/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSyncAddRepoRoute = ApiGithubSyncAddRepoRouteImport.update({
  id: '/api/github/sync/add-repo',
  path: '/api/github/sync/add-repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubOauthCallbackRoute = ApiGithubOauthCallbackRouteImport.update({
  id: '/api/github/oauth/callback',
  path: '/api/github/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullNumberRoute = OwnerRepoPullNumberRouteImport.update({
  id: '/$owner/$repo/pull/$number',
  path: '/$owner/$repo/pull/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIssuesNumberRoute = OwnerRepoIssuesNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoCommitsBranchRoute = OwnerRepoCommitsBranchRouteImport.update({
  id: '/$owner/$repo/commits/$branch',
  path: '/$owner/$repo/commits/$branch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSyncOwnerRepoRoute = ApiGithubSyncOwnerRepoRouteImport.update({
  id: '/api/github/sync/$owner/$repo',
  path: '/api/github/sync/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReadmeOwnerRepoRoute =
  ApiGithubReadmeOwnerRepoRouteImport.update({
    id: '/api/github/readme/$owner/$repo',
    path: '/api/github/readme/$owner/$repo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubBranchOwnerRepoRoute =
  ApiGithubBranchOwnerRepoRouteImport.update({
    id: '/api/github/branch/$owner/$repo',
    path: '/api/github/branch/$owner/$repo',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerRepoTreeBranchSplatRoute =
  OwnerRepoTreeBranchSplatRouteImport.update({
    id: '/$owner/$repo/tree/$branch/$',
    path: '/$owner/$repo/tree/$branch/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerRepoBlobBranchSplatRoute =
  OwnerRepoBlobBranchSplatRouteImport.update({
    id: '/$owner/$repo/blob/$branch/$',
    path: '/$owner/$repo/blob/$branch/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubSyncOwnerRepoTreeRoute =
  ApiGithubSyncOwnerRepoTreeRouteImport.update({
    id: '/tree',
    path: '/tree',
    getParentRoute: () => ApiGithubSyncOwnerRepoRoute,
  } as any)
const ApiGithubSyncOwnerRepoCommitsRoute =
  ApiGithubSyncOwnerRepoCommitsRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => ApiGithubSyncOwnerRepoRoute,
  } as any)
const ApiGithubSuggestionsOwnerRepoNumberRoute =
  ApiGithubSuggestionsOwnerRepoNumberRouteImport.update({
    id: '/api/github/suggestions/$owner/$repo/$number',
    path: '/api/github/suggestions/$owner/$repo/$number',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubReviewsOwnerRepoNumberRoute =
  ApiGithubReviewsOwnerRepoNumberRouteImport.update({
    id: '/api/github/reviews/$owner/$repo/$number',
    path: '/api/github/reviews/$owner/$repo/$number',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubReviewCommentsOwnerRepoNumberRoute =
  ApiGithubReviewCommentsOwnerRepoNumberRouteImport.update({
    id: '/api/github/review-comments/$owner/$repo/$number',
    path: '/api/github/review-comments/$owner/$repo/$number',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubResolveOwnerRepoNumberRoute =
  ApiGithubResolveOwnerRepoNumberRouteImport.update({
    id: '/api/github/resolve/$owner/$repo/$number',
    path: '/api/github/resolve/$owner/$repo/$number',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubFileOwnerRepoSplatRoute =
  ApiGithubFileOwnerRepoSplatRouteImport.update({
    id: '/api/github/file/$owner/$repo/$',
    path: '/api/github/file/$owner/$repo/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubCommentsOwnerRepoNumberRoute =
  ApiGithubCommentsOwnerRepoNumberRouteImport.update({
    id: '/api/github/comments/$owner/$repo/$number',
    path: '/api/github/comments/$owner/$repo/$number',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubSyncOwnerRepoPullNumberRoute =
  ApiGithubSyncOwnerRepoPullNumberRouteImport.update({
    id: '/pull/$number',
    path: '/pull/$number',
    getParentRoute: () => ApiGithubSyncOwnerRepoRoute,
  } as any)
const ApiGithubSyncOwnerRepoIssueNumberRoute =
  ApiGithubSyncOwnerRepoIssueNumberRouteImport.update({
    id: '/issue/$number',
    path: '/issue/$number',
    getParentRoute: () => ApiGithubSyncOwnerRepoRoute,
  } as any)
const ApiGithubPrStateOwnerRepoNumberRoute =
  ApiGithubPrStateOwnerRepoNumberRouteImport.update({
    id: '/api/github/pr/state/$owner/$repo/$number',
    path: '/api/github/pr/state/$owner/$repo/$number',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubPrMergeOwnerRepoNumberRoute =
  ApiGithubPrMergeOwnerRepoNumberRouteImport.update({
    id: '/api/github/pr/merge/$owner/$repo/$number',
    path: '/api/github/pr/merge/$owner/$repo/$number',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/api/github/permissions': typeof ApiGithubPermissionsRoute
  '/api/github/rate-limit': typeof ApiGithubRateLimitRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/webhook-health': typeof ApiGithubWebhookHealthRoute
  '/api/github/webhook-process': typeof ApiGithubWebhookProcessRoute
  '/api/github/webhook-queue': typeof ApiGithubWebhookQueueRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/commits/$branch': typeof OwnerRepoCommitsBranchRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/api/github/sync/add-repo': typeof ApiGithubSyncAddRepoRoute
  '/api/github/sync/overview': typeof ApiGithubSyncOverviewRoute
  '/api/github/sync/reset': typeof ApiGithubSyncResetRoute
  '/api/github/sync/retry': typeof ApiGithubSyncRetryRoute
  '/api/github/sync/webhooks': typeof ApiGithubSyncWebhooksRoute
  '/api/github/oauth/': typeof ApiGithubOauthIndexRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
  '/api/github/branch/$owner/$repo': typeof ApiGithubBranchOwnerRepoRoute
  '/api/github/readme/$owner/$repo': typeof ApiGithubReadmeOwnerRepoRoute
  '/api/github/sync/$owner/$repo': typeof ApiGithubSyncOwnerRepoRouteWithChildren
  '/api/github/comments/$owner/$repo/$number': typeof ApiGithubCommentsOwnerRepoNumberRoute
  '/api/github/file/$owner/$repo/$': typeof ApiGithubFileOwnerRepoSplatRoute
  '/api/github/resolve/$owner/$repo/$number': typeof ApiGithubResolveOwnerRepoNumberRoute
  '/api/github/review-comments/$owner/$repo/$number': typeof ApiGithubReviewCommentsOwnerRepoNumberRoute
  '/api/github/reviews/$owner/$repo/$number': typeof ApiGithubReviewsOwnerRepoNumberRoute
  '/api/github/suggestions/$owner/$repo/$number': typeof ApiGithubSuggestionsOwnerRepoNumberRoute
  '/api/github/sync/$owner/$repo/commits': typeof ApiGithubSyncOwnerRepoCommitsRoute
  '/api/github/sync/$owner/$repo/tree': typeof ApiGithubSyncOwnerRepoTreeRoute
  '/api/github/pr/merge/$owner/$repo/$number': typeof ApiGithubPrMergeOwnerRepoNumberRoute
  '/api/github/pr/state/$owner/$repo/$number': typeof ApiGithubPrStateOwnerRepoNumberRoute
  '/api/github/sync/$owner/$repo/issue/$number': typeof ApiGithubSyncOwnerRepoIssueNumberRoute
  '/api/github/sync/$owner/$repo/pull/$number': typeof ApiGithubSyncOwnerRepoPullNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/api/github/permissions': typeof ApiGithubPermissionsRoute
  '/api/github/rate-limit': typeof ApiGithubRateLimitRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/webhook-health': typeof ApiGithubWebhookHealthRoute
  '/api/github/webhook-process': typeof ApiGithubWebhookProcessRoute
  '/api/github/webhook-queue': typeof ApiGithubWebhookQueueRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/commits/$branch': typeof OwnerRepoCommitsBranchRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/api/github/sync/add-repo': typeof ApiGithubSyncAddRepoRoute
  '/api/github/sync/overview': typeof ApiGithubSyncOverviewRoute
  '/api/github/sync/reset': typeof ApiGithubSyncResetRoute
  '/api/github/sync/retry': typeof ApiGithubSyncRetryRoute
  '/api/github/sync/webhooks': typeof ApiGithubSyncWebhooksRoute
  '/api/github/oauth': typeof ApiGithubOauthIndexRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
  '/api/github/branch/$owner/$repo': typeof ApiGithubBranchOwnerRepoRoute
  '/api/github/readme/$owner/$repo': typeof ApiGithubReadmeOwnerRepoRoute
  '/api/github/sync/$owner/$repo': typeof ApiGithubSyncOwnerRepoRouteWithChildren
  '/api/github/comments/$owner/$repo/$number': typeof ApiGithubCommentsOwnerRepoNumberRoute
  '/api/github/file/$owner/$repo/$': typeof ApiGithubFileOwnerRepoSplatRoute
  '/api/github/resolve/$owner/$repo/$number': typeof ApiGithubResolveOwnerRepoNumberRoute
  '/api/github/review-comments/$owner/$repo/$number': typeof ApiGithubReviewCommentsOwnerRepoNumberRoute
  '/api/github/reviews/$owner/$repo/$number': typeof ApiGithubReviewsOwnerRepoNumberRoute
  '/api/github/suggestions/$owner/$repo/$number': typeof ApiGithubSuggestionsOwnerRepoNumberRoute
  '/api/github/sync/$owner/$repo/commits': typeof ApiGithubSyncOwnerRepoCommitsRoute
  '/api/github/sync/$owner/$repo/tree': typeof ApiGithubSyncOwnerRepoTreeRoute
  '/api/github/pr/merge/$owner/$repo/$number': typeof ApiGithubPrMergeOwnerRepoNumberRoute
  '/api/github/pr/state/$owner/$repo/$number': typeof ApiGithubPrStateOwnerRepoNumberRoute
  '/api/github/sync/$owner/$repo/issue/$number': typeof ApiGithubSyncOwnerRepoIssueNumberRoute
  '/api/github/sync/$owner/$repo/pull/$number': typeof ApiGithubSyncOwnerRepoPullNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/api/github/permissions': typeof ApiGithubPermissionsRoute
  '/api/github/rate-limit': typeof ApiGithubRateLimitRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/webhook-health': typeof ApiGithubWebhookHealthRoute
  '/api/github/webhook-process': typeof ApiGithubWebhookProcessRoute
  '/api/github/webhook-queue': typeof ApiGithubWebhookQueueRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/commits/$branch': typeof OwnerRepoCommitsBranchRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
  '/api/github/sync/add-repo': typeof ApiGithubSyncAddRepoRoute
  '/api/github/sync/overview': typeof ApiGithubSyncOverviewRoute
  '/api/github/sync/reset': typeof ApiGithubSyncResetRoute
  '/api/github/sync/retry': typeof ApiGithubSyncRetryRoute
  '/api/github/sync/webhooks': typeof ApiGithubSyncWebhooksRoute
  '/api/github/oauth/': typeof ApiGithubOauthIndexRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
  '/api/github/branch/$owner/$repo': typeof ApiGithubBranchOwnerRepoRoute
  '/api/github/readme/$owner/$repo': typeof ApiGithubReadmeOwnerRepoRoute
  '/api/github/sync/$owner/$repo': typeof ApiGithubSyncOwnerRepoRouteWithChildren
  '/api/github/comments/$owner/$repo/$number': typeof ApiGithubCommentsOwnerRepoNumberRoute
  '/api/github/file/$owner/$repo/$': typeof ApiGithubFileOwnerRepoSplatRoute
  '/api/github/resolve/$owner/$repo/$number': typeof ApiGithubResolveOwnerRepoNumberRoute
  '/api/github/review-comments/$owner/$repo/$number': typeof ApiGithubReviewCommentsOwnerRepoNumberRoute
  '/api/github/reviews/$owner/$repo/$number': typeof ApiGithubReviewsOwnerRepoNumberRoute
  '/api/github/suggestions/$owner/$repo/$number': typeof ApiGithubSuggestionsOwnerRepoNumberRoute
  '/api/github/sync/$owner/$repo/commits': typeof ApiGithubSyncOwnerRepoCommitsRoute
  '/api/github/sync/$owner/$repo/tree': typeof ApiGithubSyncOwnerRepoTreeRoute
  '/api/github/pr/merge/$owner/$repo/$number': typeof ApiGithubPrMergeOwnerRepoNumberRoute
  '/api/github/pr/state/$owner/$repo/$number': typeof ApiGithubPrStateOwnerRepoNumberRoute
  '/api/github/sync/$owner/$repo/issue/$number': typeof ApiGithubSyncOwnerRepoIssueNumberRoute
  '/api/github/sync/$owner/$repo/pull/$number': typeof ApiGithubSyncOwnerRepoPullNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/health'
    | '/$owner/'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/api/github/permissions'
    | '/api/github/rate-limit'
    | '/api/github/webhook'
    | '/api/github/webhook-health'
    | '/api/github/webhook-process'
    | '/api/github/webhook-queue'
    | '/$owner/$repo/'
    | '/$owner/$repo/commits/$branch'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/api/github/oauth/callback'
    | '/api/github/sync/add-repo'
    | '/api/github/sync/overview'
    | '/api/github/sync/reset'
    | '/api/github/sync/retry'
    | '/api/github/sync/webhooks'
    | '/api/github/oauth/'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
    | '/api/github/branch/$owner/$repo'
    | '/api/github/readme/$owner/$repo'
    | '/api/github/sync/$owner/$repo'
    | '/api/github/comments/$owner/$repo/$number'
    | '/api/github/file/$owner/$repo/$'
    | '/api/github/resolve/$owner/$repo/$number'
    | '/api/github/review-comments/$owner/$repo/$number'
    | '/api/github/reviews/$owner/$repo/$number'
    | '/api/github/suggestions/$owner/$repo/$number'
    | '/api/github/sync/$owner/$repo/commits'
    | '/api/github/sync/$owner/$repo/tree'
    | '/api/github/pr/merge/$owner/$repo/$number'
    | '/api/github/pr/state/$owner/$repo/$number'
    | '/api/github/sync/$owner/$repo/issue/$number'
    | '/api/github/sync/$owner/$repo/pull/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/health'
    | '/$owner'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/api/github/permissions'
    | '/api/github/rate-limit'
    | '/api/github/webhook'
    | '/api/github/webhook-health'
    | '/api/github/webhook-process'
    | '/api/github/webhook-queue'
    | '/$owner/$repo'
    | '/$owner/$repo/commits/$branch'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/api/github/oauth/callback'
    | '/api/github/sync/add-repo'
    | '/api/github/sync/overview'
    | '/api/github/sync/reset'
    | '/api/github/sync/retry'
    | '/api/github/sync/webhooks'
    | '/api/github/oauth'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
    | '/api/github/branch/$owner/$repo'
    | '/api/github/readme/$owner/$repo'
    | '/api/github/sync/$owner/$repo'
    | '/api/github/comments/$owner/$repo/$number'
    | '/api/github/file/$owner/$repo/$'
    | '/api/github/resolve/$owner/$repo/$number'
    | '/api/github/review-comments/$owner/$repo/$number'
    | '/api/github/reviews/$owner/$repo/$number'
    | '/api/github/suggestions/$owner/$repo/$number'
    | '/api/github/sync/$owner/$repo/commits'
    | '/api/github/sync/$owner/$repo/tree'
    | '/api/github/pr/merge/$owner/$repo/$number'
    | '/api/github/pr/state/$owner/$repo/$number'
    | '/api/github/sync/$owner/$repo/issue/$number'
    | '/api/github/sync/$owner/$repo/pull/$number'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/health'
    | '/$owner/'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/api/github/permissions'
    | '/api/github/rate-limit'
    | '/api/github/webhook'
    | '/api/github/webhook-health'
    | '/api/github/webhook-process'
    | '/api/github/webhook-queue'
    | '/$owner/$repo/'
    | '/$owner/$repo/commits/$branch'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/api/github/oauth/callback'
    | '/api/github/sync/add-repo'
    | '/api/github/sync/overview'
    | '/api/github/sync/reset'
    | '/api/github/sync/retry'
    | '/api/github/sync/webhooks'
    | '/api/github/oauth/'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
    | '/api/github/branch/$owner/$repo'
    | '/api/github/readme/$owner/$repo'
    | '/api/github/sync/$owner/$repo'
    | '/api/github/comments/$owner/$repo/$number'
    | '/api/github/file/$owner/$repo/$'
    | '/api/github/resolve/$owner/$repo/$number'
    | '/api/github/review-comments/$owner/$repo/$number'
    | '/api/github/reviews/$owner/$repo/$number'
    | '/api/github/suggestions/$owner/$repo/$number'
    | '/api/github/sync/$owner/$repo/commits'
    | '/api/github/sync/$owner/$repo/tree'
    | '/api/github/pr/merge/$owner/$repo/$number'
    | '/api/github/pr/state/$owner/$repo/$number'
    | '/api/github/sync/$owner/$repo/issue/$number'
    | '/api/github/sync/$owner/$repo/pull/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRouteWithChildren
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRoute
  ApiGithubPermissionsRoute: typeof ApiGithubPermissionsRoute
  ApiGithubRateLimitRoute: typeof ApiGithubRateLimitRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiGithubWebhookHealthRoute: typeof ApiGithubWebhookHealthRoute
  ApiGithubWebhookProcessRoute: typeof ApiGithubWebhookProcessRoute
  ApiGithubWebhookQueueRoute: typeof ApiGithubWebhookQueueRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoCommitsBranchRoute: typeof OwnerRepoCommitsBranchRoute
  OwnerRepoPullNumberRoute: typeof OwnerRepoPullNumberRoute
  ApiGithubOauthCallbackRoute: typeof ApiGithubOauthCallbackRoute
  ApiGithubSyncAddRepoRoute: typeof ApiGithubSyncAddRepoRoute
  ApiGithubSyncOverviewRoute: typeof ApiGithubSyncOverviewRoute
  ApiGithubSyncResetRoute: typeof ApiGithubSyncResetRoute
  ApiGithubSyncRetryRoute: typeof ApiGithubSyncRetryRoute
  ApiGithubSyncWebhooksRoute: typeof ApiGithubSyncWebhooksRoute
  ApiGithubOauthIndexRoute: typeof ApiGithubOauthIndexRoute
  OwnerRepoBlobBranchSplatRoute: typeof OwnerRepoBlobBranchSplatRoute
  OwnerRepoTreeBranchSplatRoute: typeof OwnerRepoTreeBranchSplatRoute
  ApiGithubBranchOwnerRepoRoute: typeof ApiGithubBranchOwnerRepoRoute
  ApiGithubReadmeOwnerRepoRoute: typeof ApiGithubReadmeOwnerRepoRoute
  ApiGithubSyncOwnerRepoRoute: typeof ApiGithubSyncOwnerRepoRouteWithChildren
  ApiGithubCommentsOwnerRepoNumberRoute: typeof ApiGithubCommentsOwnerRepoNumberRoute
  ApiGithubFileOwnerRepoSplatRoute: typeof ApiGithubFileOwnerRepoSplatRoute
  ApiGithubResolveOwnerRepoNumberRoute: typeof ApiGithubResolveOwnerRepoNumberRoute
  ApiGithubReviewCommentsOwnerRepoNumberRoute: typeof ApiGithubReviewCommentsOwnerRepoNumberRoute
  ApiGithubReviewsOwnerRepoNumberRoute: typeof ApiGithubReviewsOwnerRepoNumberRoute
  ApiGithubSuggestionsOwnerRepoNumberRoute: typeof ApiGithubSuggestionsOwnerRepoNumberRoute
  ApiGithubPrMergeOwnerRepoNumberRoute: typeof ApiGithubPrMergeOwnerRepoNumberRoute
  ApiGithubPrStateOwnerRepoNumberRoute: typeof ApiGithubPrStateOwnerRepoNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook-queue': {
      id: '/api/github/webhook-queue'
      path: '/api/github/webhook-queue'
      fullPath: '/api/github/webhook-queue'
      preLoaderRoute: typeof ApiGithubWebhookQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook-process': {
      id: '/api/github/webhook-process'
      path: '/api/github/webhook-process'
      fullPath: '/api/github/webhook-process'
      preLoaderRoute: typeof ApiGithubWebhookProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook-health': {
      id: '/api/github/webhook-health'
      path: '/api/github/webhook-health'
      fullPath: '/api/github/webhook-health'
      preLoaderRoute: typeof ApiGithubWebhookHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/rate-limit': {
      id: '/api/github/rate-limit'
      path: '/api/github/rate-limit'
      fullPath: '/api/github/rate-limit'
      preLoaderRoute: typeof ApiGithubRateLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/permissions': {
      id: '/api/github/permissions'
      path: '/api/github/permissions'
      fullPath: '/api/github/permissions'
      preLoaderRoute: typeof ApiGithubPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/$owner/$repo/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/oauth/': {
      id: '/api/github/oauth/'
      path: '/api/github/oauth'
      fullPath: '/api/github/oauth/'
      preLoaderRoute: typeof ApiGithubOauthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/webhooks': {
      id: '/api/github/sync/webhooks'
      path: '/api/github/sync/webhooks'
      fullPath: '/api/github/sync/webhooks'
      preLoaderRoute: typeof ApiGithubSyncWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/retry': {
      id: '/api/github/sync/retry'
      path: '/api/github/sync/retry'
      fullPath: '/api/github/sync/retry'
      preLoaderRoute: typeof ApiGithubSyncRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/reset': {
      id: '/api/github/sync/reset'
      path: '/api/github/sync/reset'
      fullPath: '/api/github/sync/reset'
      preLoaderRoute: typeof ApiGithubSyncResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/overview': {
      id: '/api/github/sync/overview'
      path: '/api/github/sync/overview'
      fullPath: '/api/github/sync/overview'
      preLoaderRoute: typeof ApiGithubSyncOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/add-repo': {
      id: '/api/github/sync/add-repo'
      path: '/api/github/sync/add-repo'
      fullPath: '/api/github/sync/add-repo'
      preLoaderRoute: typeof ApiGithubSyncAddRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/oauth/callback': {
      id: '/api/github/oauth/callback'
      path: '/api/github/oauth/callback'
      fullPath: '/api/github/oauth/callback'
      preLoaderRoute: typeof ApiGithubOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pull/$number': {
      id: '/$owner/$repo/pull/$number'
      path: '/$owner/$repo/pull/$number'
      fullPath: '/$owner/$repo/pull/$number'
      preLoaderRoute: typeof OwnerRepoPullNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/issues/$number': {
      id: '/$owner/$repo/issues/$number'
      path: '/$number'
      fullPath: '/$owner/$repo/issues/$number'
      preLoaderRoute: typeof OwnerRepoIssuesNumberRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/commits/$branch': {
      id: '/$owner/$repo/commits/$branch'
      path: '/$owner/$repo/commits/$branch'
      fullPath: '/$owner/$repo/commits/$branch'
      preLoaderRoute: typeof OwnerRepoCommitsBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/$owner/$repo': {
      id: '/api/github/sync/$owner/$repo'
      path: '/api/github/sync/$owner/$repo'
      fullPath: '/api/github/sync/$owner/$repo'
      preLoaderRoute: typeof ApiGithubSyncOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/readme/$owner/$repo': {
      id: '/api/github/readme/$owner/$repo'
      path: '/api/github/readme/$owner/$repo'
      fullPath: '/api/github/readme/$owner/$repo'
      preLoaderRoute: typeof ApiGithubReadmeOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/branch/$owner/$repo': {
      id: '/api/github/branch/$owner/$repo'
      path: '/api/github/branch/$owner/$repo'
      fullPath: '/api/github/branch/$owner/$repo'
      preLoaderRoute: typeof ApiGithubBranchOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/tree/$branch/$': {
      id: '/$owner/$repo/tree/$branch/$'
      path: '/$owner/$repo/tree/$branch/$'
      fullPath: '/$owner/$repo/tree/$branch/$'
      preLoaderRoute: typeof OwnerRepoTreeBranchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/blob/$branch/$': {
      id: '/$owner/$repo/blob/$branch/$'
      path: '/$owner/$repo/blob/$branch/$'
      fullPath: '/$owner/$repo/blob/$branch/$'
      preLoaderRoute: typeof OwnerRepoBlobBranchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/$owner/$repo/tree': {
      id: '/api/github/sync/$owner/$repo/tree'
      path: '/tree'
      fullPath: '/api/github/sync/$owner/$repo/tree'
      preLoaderRoute: typeof ApiGithubSyncOwnerRepoTreeRouteImport
      parentRoute: typeof ApiGithubSyncOwnerRepoRoute
    }
    '/api/github/sync/$owner/$repo/commits': {
      id: '/api/github/sync/$owner/$repo/commits'
      path: '/commits'
      fullPath: '/api/github/sync/$owner/$repo/commits'
      preLoaderRoute: typeof ApiGithubSyncOwnerRepoCommitsRouteImport
      parentRoute: typeof ApiGithubSyncOwnerRepoRoute
    }
    '/api/github/suggestions/$owner/$repo/$number': {
      id: '/api/github/suggestions/$owner/$repo/$number'
      path: '/api/github/suggestions/$owner/$repo/$number'
      fullPath: '/api/github/suggestions/$owner/$repo/$number'
      preLoaderRoute: typeof ApiGithubSuggestionsOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/reviews/$owner/$repo/$number': {
      id: '/api/github/reviews/$owner/$repo/$number'
      path: '/api/github/reviews/$owner/$repo/$number'
      fullPath: '/api/github/reviews/$owner/$repo/$number'
      preLoaderRoute: typeof ApiGithubReviewsOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/review-comments/$owner/$repo/$number': {
      id: '/api/github/review-comments/$owner/$repo/$number'
      path: '/api/github/review-comments/$owner/$repo/$number'
      fullPath: '/api/github/review-comments/$owner/$repo/$number'
      preLoaderRoute: typeof ApiGithubReviewCommentsOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/resolve/$owner/$repo/$number': {
      id: '/api/github/resolve/$owner/$repo/$number'
      path: '/api/github/resolve/$owner/$repo/$number'
      fullPath: '/api/github/resolve/$owner/$repo/$number'
      preLoaderRoute: typeof ApiGithubResolveOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/file/$owner/$repo/$': {
      id: '/api/github/file/$owner/$repo/$'
      path: '/api/github/file/$owner/$repo/$'
      fullPath: '/api/github/file/$owner/$repo/$'
      preLoaderRoute: typeof ApiGithubFileOwnerRepoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/comments/$owner/$repo/$number': {
      id: '/api/github/comments/$owner/$repo/$number'
      path: '/api/github/comments/$owner/$repo/$number'
      fullPath: '/api/github/comments/$owner/$repo/$number'
      preLoaderRoute: typeof ApiGithubCommentsOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/$owner/$repo/pull/$number': {
      id: '/api/github/sync/$owner/$repo/pull/$number'
      path: '/pull/$number'
      fullPath: '/api/github/sync/$owner/$repo/pull/$number'
      preLoaderRoute: typeof ApiGithubSyncOwnerRepoPullNumberRouteImport
      parentRoute: typeof ApiGithubSyncOwnerRepoRoute
    }
    '/api/github/sync/$owner/$repo/issue/$number': {
      id: '/api/github/sync/$owner/$repo/issue/$number'
      path: '/issue/$number'
      fullPath: '/api/github/sync/$owner/$repo/issue/$number'
      preLoaderRoute: typeof ApiGithubSyncOwnerRepoIssueNumberRouteImport
      parentRoute: typeof ApiGithubSyncOwnerRepoRoute
    }
    '/api/github/pr/state/$owner/$repo/$number': {
      id: '/api/github/pr/state/$owner/$repo/$number'
      path: '/api/github/pr/state/$owner/$repo/$number'
      fullPath: '/api/github/pr/state/$owner/$repo/$number'
      preLoaderRoute: typeof ApiGithubPrStateOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/pr/merge/$owner/$repo/$number': {
      id: '/api/github/pr/merge/$owner/$repo/$number'
      path: '/api/github/pr/merge/$owner/$repo/$number'
      fullPath: '/api/github/pr/merge/$owner/$repo/$number'
      preLoaderRoute: typeof ApiGithubPrMergeOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OwnerRepoIssuesRouteChildren {
  OwnerRepoIssuesNumberRoute: typeof OwnerRepoIssuesNumberRoute
}

const OwnerRepoIssuesRouteChildren: OwnerRepoIssuesRouteChildren = {
  OwnerRepoIssuesNumberRoute: OwnerRepoIssuesNumberRoute,
}

const OwnerRepoIssuesRouteWithChildren = OwnerRepoIssuesRoute._addFileChildren(
  OwnerRepoIssuesRouteChildren,
)

interface ApiGithubSyncOwnerRepoRouteChildren {
  ApiGithubSyncOwnerRepoCommitsRoute: typeof ApiGithubSyncOwnerRepoCommitsRoute
  ApiGithubSyncOwnerRepoTreeRoute: typeof ApiGithubSyncOwnerRepoTreeRoute
  ApiGithubSyncOwnerRepoIssueNumberRoute: typeof ApiGithubSyncOwnerRepoIssueNumberRoute
  ApiGithubSyncOwnerRepoPullNumberRoute: typeof ApiGithubSyncOwnerRepoPullNumberRoute
}

const ApiGithubSyncOwnerRepoRouteChildren: ApiGithubSyncOwnerRepoRouteChildren =
  {
    ApiGithubSyncOwnerRepoCommitsRoute: ApiGithubSyncOwnerRepoCommitsRoute,
    ApiGithubSyncOwnerRepoTreeRoute: ApiGithubSyncOwnerRepoTreeRoute,
    ApiGithubSyncOwnerRepoIssueNumberRoute:
      ApiGithubSyncOwnerRepoIssueNumberRoute,
    ApiGithubSyncOwnerRepoPullNumberRoute:
      ApiGithubSyncOwnerRepoPullNumberRoute,
  }

const ApiGithubSyncOwnerRepoRouteWithChildren =
  ApiGithubSyncOwnerRepoRoute._addFileChildren(
    ApiGithubSyncOwnerRepoRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRouteWithChildren,
  OwnerRepoPullsRoute: OwnerRepoPullsRoute,
  ApiGithubPermissionsRoute: ApiGithubPermissionsRoute,
  ApiGithubRateLimitRoute: ApiGithubRateLimitRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiGithubWebhookHealthRoute: ApiGithubWebhookHealthRoute,
  ApiGithubWebhookProcessRoute: ApiGithubWebhookProcessRoute,
  ApiGithubWebhookQueueRoute: ApiGithubWebhookQueueRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoCommitsBranchRoute: OwnerRepoCommitsBranchRoute,
  OwnerRepoPullNumberRoute: OwnerRepoPullNumberRoute,
  ApiGithubOauthCallbackRoute: ApiGithubOauthCallbackRoute,
  ApiGithubSyncAddRepoRoute: ApiGithubSyncAddRepoRoute,
  ApiGithubSyncOverviewRoute: ApiGithubSyncOverviewRoute,
  ApiGithubSyncResetRoute: ApiGithubSyncResetRoute,
  ApiGithubSyncRetryRoute: ApiGithubSyncRetryRoute,
  ApiGithubSyncWebhooksRoute: ApiGithubSyncWebhooksRoute,
  ApiGithubOauthIndexRoute: ApiGithubOauthIndexRoute,
  OwnerRepoBlobBranchSplatRoute: OwnerRepoBlobBranchSplatRoute,
  OwnerRepoTreeBranchSplatRoute: OwnerRepoTreeBranchSplatRoute,
  ApiGithubBranchOwnerRepoRoute: ApiGithubBranchOwnerRepoRoute,
  ApiGithubReadmeOwnerRepoRoute: ApiGithubReadmeOwnerRepoRoute,
  ApiGithubSyncOwnerRepoRoute: ApiGithubSyncOwnerRepoRouteWithChildren,
  ApiGithubCommentsOwnerRepoNumberRoute: ApiGithubCommentsOwnerRepoNumberRoute,
  ApiGithubFileOwnerRepoSplatRoute: ApiGithubFileOwnerRepoSplatRoute,
  ApiGithubResolveOwnerRepoNumberRoute: ApiGithubResolveOwnerRepoNumberRoute,
  ApiGithubReviewCommentsOwnerRepoNumberRoute:
    ApiGithubReviewCommentsOwnerRepoNumberRoute,
  ApiGithubReviewsOwnerRepoNumberRoute: ApiGithubReviewsOwnerRepoNumberRoute,
  ApiGithubSuggestionsOwnerRepoNumberRoute:
    ApiGithubSuggestionsOwnerRepoNumberRoute,
  ApiGithubPrMergeOwnerRepoNumberRoute: ApiGithubPrMergeOwnerRepoNumberRoute,
  ApiGithubPrStateOwnerRepoNumberRoute: ApiGithubPrStateOwnerRepoNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
