/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/$owner/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubRateLimitRouteImport } from './routes/api/github/rate-limit'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner/$repo/pulls'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner/$repo/issues'
import { Route as ApiGithubSyncOverviewRouteImport } from './routes/api/github/sync/overview'
import { Route as OwnerRepoPullNumberRouteImport } from './routes/$owner/$repo/pull.$number'
import { Route as OwnerRepoIssuesNumberRouteImport } from './routes/$owner/$repo/issues.$number'
import { Route as ApiGithubSyncOwnerRepoRouteImport } from './routes/api/github/sync/$owner.$repo'
import { Route as OwnerRepoTreeBranchSplatRouteImport } from './routes/$owner/$repo/tree.$branch.$'
import { Route as OwnerRepoBlobBranchSplatRouteImport } from './routes/$owner/$repo/blob.$branch.$'
import { Route as ApiGithubSyncOwnerRepoPullNumberRouteImport } from './routes/api/github/sync/$owner.$repo.pull.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRateLimitRoute = ApiGithubRateLimitRouteImport.update({
  id: '/api/github/rate-limit',
  path: '/api/github/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/$owner/$repo/issues',
  path: '/$owner/$repo/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSyncOverviewRoute = ApiGithubSyncOverviewRouteImport.update({
  id: '/api/github/sync/overview',
  path: '/api/github/sync/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullNumberRoute = OwnerRepoPullNumberRouteImport.update({
  id: '/$owner/$repo/pull/$number',
  path: '/$owner/$repo/pull/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIssuesNumberRoute = OwnerRepoIssuesNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const ApiGithubSyncOwnerRepoRoute = ApiGithubSyncOwnerRepoRouteImport.update({
  id: '/api/github/sync/$owner/$repo',
  path: '/api/github/sync/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoTreeBranchSplatRoute =
  OwnerRepoTreeBranchSplatRouteImport.update({
    id: '/$owner/$repo/tree/$branch/$',
    path: '/$owner/$repo/tree/$branch/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerRepoBlobBranchSplatRoute =
  OwnerRepoBlobBranchSplatRouteImport.update({
    id: '/$owner/$repo/blob/$branch/$',
    path: '/$owner/$repo/blob/$branch/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubSyncOwnerRepoPullNumberRoute =
  ApiGithubSyncOwnerRepoPullNumberRouteImport.update({
    id: '/pull/$number',
    path: '/pull/$number',
    getParentRoute: () => ApiGithubSyncOwnerRepoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/api/github/rate-limit': typeof ApiGithubRateLimitRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/api/github/sync/overview': typeof ApiGithubSyncOverviewRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
  '/api/github/sync/$owner/$repo': typeof ApiGithubSyncOwnerRepoRouteWithChildren
  '/api/github/sync/$owner/$repo/pull/$number': typeof ApiGithubSyncOwnerRepoPullNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/api/github/rate-limit': typeof ApiGithubRateLimitRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/api/github/sync/overview': typeof ApiGithubSyncOverviewRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
  '/api/github/sync/$owner/$repo': typeof ApiGithubSyncOwnerRepoRouteWithChildren
  '/api/github/sync/$owner/$repo/pull/$number': typeof ApiGithubSyncOwnerRepoPullNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/api/github/rate-limit': typeof ApiGithubRateLimitRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/api/github/sync/overview': typeof ApiGithubSyncOverviewRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
  '/api/github/sync/$owner/$repo': typeof ApiGithubSyncOwnerRepoRouteWithChildren
  '/api/github/sync/$owner/$repo/pull/$number': typeof ApiGithubSyncOwnerRepoPullNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/$owner'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/api/github/rate-limit'
    | '/api/github/webhook'
    | '/$owner/$repo'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/api/github/sync/overview'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
    | '/api/github/sync/$owner/$repo'
    | '/api/github/sync/$owner/$repo/pull/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/$owner'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/api/github/rate-limit'
    | '/api/github/webhook'
    | '/$owner/$repo'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/api/github/sync/overview'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
    | '/api/github/sync/$owner/$repo'
    | '/api/github/sync/$owner/$repo/pull/$number'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/$owner/'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/api/github/rate-limit'
    | '/api/github/webhook'
    | '/$owner/$repo/'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/api/github/sync/overview'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
    | '/api/github/sync/$owner/$repo'
    | '/api/github/sync/$owner/$repo/pull/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRouteWithChildren
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRoute
  ApiGithubRateLimitRoute: typeof ApiGithubRateLimitRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoPullNumberRoute: typeof OwnerRepoPullNumberRoute
  ApiGithubSyncOverviewRoute: typeof ApiGithubSyncOverviewRoute
  OwnerRepoBlobBranchSplatRoute: typeof OwnerRepoBlobBranchSplatRoute
  OwnerRepoTreeBranchSplatRoute: typeof OwnerRepoTreeBranchSplatRoute
  ApiGithubSyncOwnerRepoRoute: typeof ApiGithubSyncOwnerRepoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/rate-limit': {
      id: '/api/github/rate-limit'
      path: '/api/github/rate-limit'
      fullPath: '/api/github/rate-limit'
      preLoaderRoute: typeof ApiGithubRateLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/$owner/$repo/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/overview': {
      id: '/api/github/sync/overview'
      path: '/api/github/sync/overview'
      fullPath: '/api/github/sync/overview'
      preLoaderRoute: typeof ApiGithubSyncOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pull/$number': {
      id: '/$owner/$repo/pull/$number'
      path: '/$owner/$repo/pull/$number'
      fullPath: '/$owner/$repo/pull/$number'
      preLoaderRoute: typeof OwnerRepoPullNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/issues/$number': {
      id: '/$owner/$repo/issues/$number'
      path: '/$number'
      fullPath: '/$owner/$repo/issues/$number'
      preLoaderRoute: typeof OwnerRepoIssuesNumberRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/api/github/sync/$owner/$repo': {
      id: '/api/github/sync/$owner/$repo'
      path: '/api/github/sync/$owner/$repo'
      fullPath: '/api/github/sync/$owner/$repo'
      preLoaderRoute: typeof ApiGithubSyncOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/tree/$branch/$': {
      id: '/$owner/$repo/tree/$branch/$'
      path: '/$owner/$repo/tree/$branch/$'
      fullPath: '/$owner/$repo/tree/$branch/$'
      preLoaderRoute: typeof OwnerRepoTreeBranchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/blob/$branch/$': {
      id: '/$owner/$repo/blob/$branch/$'
      path: '/$owner/$repo/blob/$branch/$'
      fullPath: '/$owner/$repo/blob/$branch/$'
      preLoaderRoute: typeof OwnerRepoBlobBranchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync/$owner/$repo/pull/$number': {
      id: '/api/github/sync/$owner/$repo/pull/$number'
      path: '/pull/$number'
      fullPath: '/api/github/sync/$owner/$repo/pull/$number'
      preLoaderRoute: typeof ApiGithubSyncOwnerRepoPullNumberRouteImport
      parentRoute: typeof ApiGithubSyncOwnerRepoRoute
    }
  }
}

interface OwnerRepoIssuesRouteChildren {
  OwnerRepoIssuesNumberRoute: typeof OwnerRepoIssuesNumberRoute
}

const OwnerRepoIssuesRouteChildren: OwnerRepoIssuesRouteChildren = {
  OwnerRepoIssuesNumberRoute: OwnerRepoIssuesNumberRoute,
}

const OwnerRepoIssuesRouteWithChildren = OwnerRepoIssuesRoute._addFileChildren(
  OwnerRepoIssuesRouteChildren,
)

interface ApiGithubSyncOwnerRepoRouteChildren {
  ApiGithubSyncOwnerRepoPullNumberRoute: typeof ApiGithubSyncOwnerRepoPullNumberRoute
}

const ApiGithubSyncOwnerRepoRouteChildren: ApiGithubSyncOwnerRepoRouteChildren =
  {
    ApiGithubSyncOwnerRepoPullNumberRoute:
      ApiGithubSyncOwnerRepoPullNumberRoute,
  }

const ApiGithubSyncOwnerRepoRouteWithChildren =
  ApiGithubSyncOwnerRepoRoute._addFileChildren(
    ApiGithubSyncOwnerRepoRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRouteWithChildren,
  OwnerRepoPullsRoute: OwnerRepoPullsRoute,
  ApiGithubRateLimitRoute: ApiGithubRateLimitRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoPullNumberRoute: OwnerRepoPullNumberRoute,
  ApiGithubSyncOverviewRoute: ApiGithubSyncOverviewRoute,
  OwnerRepoBlobBranchSplatRoute: OwnerRepoBlobBranchSplatRoute,
  OwnerRepoTreeBranchSplatRoute: OwnerRepoTreeBranchSplatRoute,
  ApiGithubSyncOwnerRepoRoute: ApiGithubSyncOwnerRepoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
