/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/$owner/index'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner/$repo/pulls'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner/$repo/issues'
import { Route as OwnerRepoPullNumberRouteImport } from './routes/$owner/$repo/pull.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/$owner/$repo/issues',
  path: '/$owner/$repo/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullNumberRoute = OwnerRepoPullNumberRouteImport.update({
  id: '/$owner/$repo/pull/$number',
  path: '/$owner/$repo/pull/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$owner'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo'
    | '/$owner/$repo/pull/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$owner'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo'
    | '/$owner/$repo/pull/$number'
  id:
    | '__root__'
    | '/'
    | '/$owner/'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/'
    | '/$owner/$repo/pull/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRoute
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoPullNumberRoute: typeof OwnerRepoPullNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/$owner/$repo/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pull/$number': {
      id: '/$owner/$repo/pull/$number'
      path: '/$owner/$repo/pull/$number'
      fullPath: '/$owner/$repo/pull/$number'
      preLoaderRoute: typeof OwnerRepoPullNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRoute,
  OwnerRepoPullsRoute: OwnerRepoPullsRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoPullNumberRoute: OwnerRepoPullNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
